/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/test.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Empty001" position={[11, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.26}>
          <group name="Camera" scale={3.78}>
            <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={22.9} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
        </group>
        <mesh geometry={nodes.Text001.geometry} material={materials['Cardboard 01']} position={[-13.21, -1.27, 3.59]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.24} />
        <mesh geometry={nodes.Text002.geometry} material={materials['Cardboard 01']} position={[0, 0, 3.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.24} />
        <mesh name="Text003" geometry={nodes.Text003.geometry} material={materials['Material.001']} position={[11, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.26} />
        <mesh geometry={nodes.Text004.geometry} material={materials['Cardboard 01']} position={[-43.71, 11.79, 15.86]} rotation={[1.46, -0.29, -1.95]} scale={2.57} />
      </group>
    </group>
  )
}

useGLTF.preload('/test.glb')
